# Generated by Django 2.1.5 on 2019-02-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_daate',
            new_name='pub_date',
        ),
    ]
